name: CI

on:
  pull_request:
    branches:
      - master
      - release
    types:
      - opened
      - reopened
      - synchronize
      - edited
env:
  node_version: "14.x"

jobs:
  test:
    name: Test Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        run: npm install

      - name: npm test
        run: |
          npm test
          npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  audit:
    name: Audit App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm audit
        run: npm audit --audit-level=critical

  lint:
    name: Lint App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint