name: CI

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - edited
env:
  node_version: "18.x"

jobs:
  test:
    name: Test Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: npm install
      - run: npm run test:coverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          slug: byu-oit/env-ssm

  lint:
    name: Lint Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: npm install
      - run: npm run lint

  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: npm install
      - run: npm run build
