name: Publish

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "publish"
  cancel-in-progress: false

env:
  node_version: "18.x"

jobs:
  publish:
    name: Publish node package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - token: NPM_TOKEN
            url: https://registry.npmjs.org
          - token: GITHUB_TOKEN
            url: https://npm.pkg.github.com
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: ${{ matrix.registry.url }}
          scope: '@byu-oit'

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}

        # The prepublishOnly script builds the package before publishing
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
